In [1]:
import pandas as pd
import pickle
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
from operator import truediv

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
test_preds = pd.read_pickle("/mnt/data/Users/A-PROOF/Cecilia_S/models/fine_tuned/binary/test_set_pos_ell_sh_hq1.pkl")

In [4]:
test_preds

pad_sen_id  year NotitieID                batch annotator  \
0109003_0003    0109003_0003  2020   0109003         ergotherapie     edwin   
0119003_0001    0119003_0001  2020   0119003         ergotherapie     edwin   
0131001_0005    0131001_0005  2020   0131001        fysiotherapie   meskers   
0131001_0011    0131001_0011  2020   0131001        fysiotherapie   meskers   
0131001_0012    0131001_0012  2020   0131001        fysiotherapie   meskers   
...                      ...   ...       ...                  ...       ...   
79472723_0010  79472723_0010  2016  79472723        lung_patients     edwin   
79472723_0012  79472723_0012  2016  79472723        lung_patients     edwin   
79472723_0017  79472723_0017  2016  79472723        lung_patients     edwin   
79472723_0021  79472723_0021  2016  79472723        lung_patients     edwin   
84588639_0001  84588639_0001  2016  84588639  lung_patient_batch3     edwin   

               background_sent  target_sent  \
0109003_0003             False        False   
0119003_0001             False        False   
0131001_0005             False        False   
0131001_0011             False        False   
0131001_0012             False         True   
...                        ...          ...   
79472723_0010            False        False   
79472723_0012            False        False   
79472723_0017            False        False   
79472723_0021            False         True   
84588639_0001            False        False   

                                                                                                                                                                                                                                                text_raw  \
0109003_0003                                                                                                                           al ze even klaar mee is , wordt ze moe , zware schouders en gaat stoppen met activiteit , even naar buiten . Laad   
0119003_0001                                                                                                                               beoordeling therapeut vermoeidheid neemt iets af , benauwdheid/pijn op de borst blijft nog wel bij inspannign   
0131001_0005                                                                                                                                                                                                             met 2 uur werken per dag . komt   
0131001_0011                                                                                                                                         moe , zwaar werk vandaag gehad , ook iets langer dan 2 uur gewerkt , weinig kracht in handen . gaat   
0131001_0012                                                                                                                                                                           vragen of hij nog een weekje 2 uur per dag kan werken . evalueert   
...                                                                                                                                                                                                                                                  ...   
79472723_0010          Daarnaast geadviseerd de warme maaltijd niet zelf klaar te maken omdat geur alleen al voor anorexie kan zorgen . Daarnaast geadviseerd de warme maaltijd niet zelf klaar te maken omdat geur alleen al voor anorexie kan zorgen .   
79472723_0012                                Man met zeer slechte voedingstoestand , wasting / cachectisch beeld obv -20 % tov gebruikelijk , wb . Man met zeer slechte voedingstoestand , wasting / cachectisch beeld obv -20 % tov gebruikelijk , wb .   
79472723_0017                                                                                                                Huidige intake < 50 % vd geschatte energie- & eiwitbehoefte . Huidige intake < 50 % vd geschatte energie- & eiw

In [5]:
test_preds['domain_pred'] = ""

In [6]:
test_preds['domain_gold'] = ""

In [7]:
for ri, row in test_preds.iterrows():
    if row['pred_hq_data1'] == [1, 0, 0, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'ADM'
    if row['pred_hq_data1'] == [0, 1, 0, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'ATT'
    if row['pred_hq_data1'] == [0, 0, 1, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'BER'
    if row['pred_hq_data1'] == [0, 0, 0, 1, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'ENR'
    if row['pred_hq_data1'] == [0, 0, 0, 0, 1, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'ETN'
    if row['pred_hq_data1'] == [0, 0, 0, 0, 0, 1, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'FAC'
    if row['pred_hq_data1'] == [0, 0, 0, 0, 0, 0, 1, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'INS'
    if row['pred_hq_data1'] == [0, 0, 0, 0, 0, 0, 0, 1, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'MBW'
    if row['pred_hq_data1'] == [0, 0, 0, 0, 0, 0, 0, 0, 1]:
        test_preds.loc[ri, 'domain_pred'] = 'STM'
    #if row['pred_hq_data1'] == [0, 0, 0, 0, 0, 0, 0, 0, 0]:
     #   test_preds.loc[ri, 'domain_pred'] = 'O'

In [8]:
for ri, row in test_preds.iterrows():
    if row['labels'] == [1, 0, 0, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'ADM'
    if row['labels'] == [0, 1, 0, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'ATT'
    if row['labels'] == [0, 0, 1, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'BER'
    if row['labels'] == [0, 0, 0, 1, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'ENR'
    if row['labels'] == [0, 0, 0, 0, 1, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'ETN'
    if row['labels'] == [0, 0, 0, 0, 0, 1, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'FAC'
    if row['labels'] == [0, 0, 0, 0, 0, 0, 1, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'INS'
    if row['labels'] == [0, 0, 0, 0, 0, 0, 0, 1, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'MBW'
    if row['labels'] == [0, 0, 0, 0, 0, 0, 0, 0, 1]:
        test_preds.loc[ri, 'domain_gold'] = 'STM'
    #if row['labels'] == [0, 0, 0, 0, 0, 0, 0, 0, 0]:
     #   test_preds.loc[ri, 'domain_gold'] = 'O'

In [9]:
test_preds

pad_sen_id  year NotitieID                batch annotator  \
0109003_0003    0109003_0003  2020   0109003         ergotherapie     edwin   
0119003_0001    0119003_0001  2020   0119003         ergotherapie     edwin   
0131001_0005    0131001_0005  2020   0131001        fysiotherapie   meskers   
0131001_0011    0131001_0011  2020   0131001        fysiotherapie   meskers   
0131001_0012    0131001_0012  2020   0131001        fysiotherapie   meskers   
...                      ...   ...       ...                  ...       ...   
79472723_0010  79472723_0010  2016  79472723        lung_patients     edwin   
79472723_0012  79472723_0012  2016  79472723        lung_patients     edwin   
79472723_0017  79472723_0017  2016  79472723        lung_patients     edwin   
79472723_0021  79472723_0021  2016  79472723        lung_patients     edwin   
84588639_0001  84588639_0001  2016  84588639  lung_patient_batch3     edwin   

               background_sent  target_sent  \
0109003_0003             False        False   
0119003_0001             False        False   
0131001_0005             False        False   
0131001_0011             False        False   
0131001_0012             False         True   
...                        ...          ...   
79472723_0010            False        False   
79472723_0012            False        False   
79472723_0017            False        False   
79472723_0021            False         True   
84588639_0001            False        False   

                                                                                                                                                                                                                                                text_raw  \
0109003_0003                                                                                                                           al ze even klaar mee is , wordt ze moe , zware schouders en gaat stoppen met activiteit , even naar buiten . Laad   
0119003_0001                                                                                                                               beoordeling therapeut vermoeidheid neemt iets af , benauwdheid/pijn op de borst blijft nog wel bij inspannign   
0131001_0005                                                                                                                                                                                                             met 2 uur werken per dag . komt   
0131001_0011                                                                                                                                         moe , zwaar werk vandaag gehad , ook iets langer dan 2 uur gewerkt , weinig kracht in handen . gaat   
0131001_0012                                                                                                                                                                           vragen of hij nog een weekje 2 uur per dag kan werken . evalueert   
...                                                                                                                                                                                                                                                  ...   
79472723_0010          Daarnaast geadviseerd de warme maaltijd niet zelf klaar te maken omdat geur alleen al voor anorexie kan zorgen . Daarnaast geadviseerd de warme maaltijd niet zelf klaar te maken omdat geur alleen al voor anorexie kan zorgen .   
79472723_0012                                Man met zeer slechte voedingstoestand , wasting / cachectisch beeld obv -20 % tov gebruikelijk , wb . Man met zeer slechte voedingstoestand , wasting / cachectisch beeld obv -20 % tov gebruikelijk , wb .   
79472723_0017                                                                                                                Huidige intake < 50 % vd geschatte energie- & eiwitbehoefte . Huidige intake < 50 % vd geschatte energie- & eiw

In [10]:
y_pred = test_preds['domain_pred'].tolist()
y_true = test_preds['domain_gold'].tolist()

In [11]:
unique_labels = np.unique([y_true, y_pred])
cmtx = pd.DataFrame(
    confusion_matrix(y_true, y_pred, labels=unique_labels),
    index=['true:{:}'.format(x) for x in unique_labels],
    columns=['pred:{:}'.format(x) for x in unique_labels]
)

cmtx

pred:  pred:ADM  pred:ATT  pred:BER  pred:ENR  pred:ETN  pred:FAC  \
true:       118        51         1        18        35       164       105   
true:ADM     11       304         0         0         0         0         1   
true:ATT      1         0         9         0         0         0         0   
true:BER      1         0         0        15         0         0         0   
true:ENR      5         0         0         0       105         1         1   
true:ETN      6         1         0         0         0       253         2   
true:FAC      7         0         0         0         0         0       163   
true:INS      6         2         0         1         2         1         9   
true:MBW     15         0         0         0         0         7         0   
true:STM      1         0         0         0         1         0         0   

          pred:INS  pred:MBW  pred:STM  
true:           69        69        65  
true:ADM         2         0         1  
true:ATT         0         0         1  
true:BER         0         0         0  
true:ENR         1         0         0  
true:ETN         0         2         1  
true:FAC         1         0         0  
true:INS        74         1         0  
true:MBW         1       122         0  
true:STM         0         2       130

In [12]:
cf = cmtx.to_numpy()

In [13]:
tp = np.diag(cf)

precision = list(map(truediv, tp, np.sum(cf, axis = 0)))
recall = list(map(truediv, tp, np.sum(cf, axis = 1)))
f1 = []

for p, r in list(zip(precision, recall)):
    f = (2*p*r)/(p+r)
    f1.append(f)

#print('Precision: {}\nRecall: {}\nF1 score: {}'.format(precision, recall, f1))

In [14]:
results = pd.DataFrame([precision,
                       recall,
                       f1],
                      columns=['O', 'ADM', 'ATT', 'BER', 'ENR', 'ETN', 'FAC', 'INS', 'MBW', 'STM'],
                      index=['Precision','Recall', 'F1 score'])

results

O       ADM       ATT       BER       ENR       ETN  \
Precision  0.690058  0.849162  0.900000  0.441176  0.734266  0.593897   
Recall     0.169784  0.952978  0.818182  0.937500  0.929204  0.954717   
F1 score   0.272517  0.898080  0.857143  0.600000  0.820312  0.732272   

                FAC       INS       MBW       STM  
Precision  0.580071  0.500000  0.622449  0.656566  
Recall     0.953216  0.770833  0.841379  0.970149  
F1 score   0.721239  0.606557  0.715543  0.783133

In [15]:
results.to_pickle("/mnt/data/Users/A-PROOF/Cecilia_S/models/fine_tuned/best_model/results_ell_sh_hq1.pkl")

In [16]:
domains = ['O', 'ADM', 'ATT', 'BER', 'ENR', 'ETN', 'FAC', 'INS', 'MBW', 'STM']

for d, p, r, f in list(zip(domains, precision, recall, f1)):
    print('{}\nPrecision: {}\nRecall: {}\nF1 score: {}\n'.format(d, p, r, f))

O
Precision: 0.6900584795321637
Recall: 0.1697841726618705
F1 score: 0.27251732101616627

ADM
Precision: 0.8491620111731844
Recall: 0.9529780564263323
F1 score: 0.8980797636632201

ATT
Precision: 0.9
Recall: 0.8181818181818182
F1 score: 0.8571428571428572

BER
Precision: 0.4411764705882353
Recall: 0.9375
F1 score: 0.6

ENR
Precision: 0.7342657342657343
Recall: 0.9292035398230089
F1 score: 0.8203125

ETN
Precision: 0.5938967136150235
Recall: 0.9547169811320755
F1 score: 0.7322720694645442

FAC
Precision: 0.5800711743772242
Recall: 0.9532163742690059
F1 score: 0.7212389380530974

INS
Precision: 0.5
Recall: 0.7708333333333334
F1 score: 0.6065573770491803

MBW
Precision: 0.6224489795918368
Recall: 0.8413793103448276
F1 score: 0.7155425219941349

STM
Precision: 0.6565656565656566
Recall: 0.9701492537313433
F1 score: 0.7831325301204819



In [16]:
counter = 0

for ri, row in test_preds.iterrows():
    if row['domain_gold'] == '' and row['domain_pred'] == '':
        counter += 1
        
print(counter)

57


### Old

In [32]:
cf_matrix = confusion_matrix(y_true, y_pred)

In [33]:
print(cf_matrix)

[[ 15   9   0   2   6   2  15  12   6   1   2]
 [  7 172   0   0   1   0   1   1   0   0   0]
 [  0   0   8   0   0   0   1   0   0   0   0]
 [  0   0   0   6   0   0   0   0   0   1   0]
 [  2   0   0   0  51   1   0   0   0   0   0]
 [  0   1   0   0   0  81   2   0   0   0   0]
 [  1   1   0   0   0   0  83   0   0   0   0]
 [  2   1   0   0   1   0   7  25   0   0   0]
 [  1   0   0   0   0   0   0   0  39   0   0]
 [ 20  91   1   8  22 109 100  33  30  21  49]
 [  0   0   0   0   1   0   0   0   1   1  94]]
