In [1]:
import pandas as pd
import pickle
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
from operator import truediv

In [2]:
model_outputs = pd.read_pickle("/mnt/data/Users/A-PROOF/Cecilia_S/models/fine_tuned/hq_data1/model_outputs.pkl")

In [4]:
print(model_outputs)

[[2.62413756e-03 8.99701030e-04 1.41362345e-03 ... 1.86247786e-03
  9.87661537e-04 9.95982528e-01]
 [2.64369627e-03 9.11893090e-04 1.62986817e-03 ... 1.91076705e-03
  1.03978347e-03 9.96122897e-01]
 [2.93881120e-03 1.03319914e-03 1.69045071e-03 ... 1.82569877e-03
  1.04561739e-03 9.96330678e-01]
 ...
 [9.96154130e-01 9.00400337e-04 9.56159551e-04 ... 1.56624964e-03
  1.14957930e-03 4.36264090e-03]
 [9.96262729e-01 7.63322168e-04 9.02389060e-04 ... 1.83961936e-03
  1.17593911e-03 3.12400633e-03]
 [9.96082246e-01 8.15964479e-04 9.69423505e-04 ... 1.60722178e-03
  1.23511313e-03 3.13926325e-03]]


In [5]:
wrong_preds = pd.read_pickle("/mnt/data/Users/A-PROOF/Cecilia_S/models/fine_tuned/hq_data1/wrong_preds.pkl")

In [6]:
wrong_preds

[]

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
test_preds = pd.read_pickle("/mnt/data/Users/A-PROOF/Cecilia_S/models/fine_tuned/binary/test_set_pos_hq.pkl")

In [4]:
test_preds

text  \
821                                                                         Anamnese M is wel nerveus over dit gesprek , bang dat we iets doorvertellen aan instanties .   
827                                                                                                                M is niet bang , wil ook geen aangifte of scheiding .   
831                                                             Heeft het vechten nooit gezien , maar ziet wel dat moeder dan boos is , heeft het mogelijk ook gehoord .   
832                                                                         PERSON is nooit geslagen , P is niet boos op de kinderen , alleen op PERSON slaat ook niet .   
834                                                                                                                                           PERSON lijkt wel bezorgd .   
...                                                                                                                                                                  ...   
215368                                                                                                                                         Ondervoeding - SNAQ Score   
215369                                                                                                                                                              SNAQ   
216714                                                                                                                                              37,4 ° C | Ademhal .   
216744                                                                                                                                                    Geen dyspnoe .   
217791  Bloeddruk 117/75 , polsfrequentie 110 , temperatuur 35,5 ° C , temperatuurbron PERSON , ademhalingsfrequentie 14 , lengte 170 cm , gewicht 76,8 kg , SpO2 97 % .   

                             labels      pad_sen_id institution  year  \
821     [0, 0, 0, 0, 0, 0, 0, 0, 1]  237672660_0033         amc  2018   
827     [0, 0, 0, 0, 0, 0, 0, 0, 1]  237672660_0039         amc  2018   
831     [0, 0, 0, 0, 0, 0, 0, 0, 1]  237672660_0043         amc  2018   
832     [0, 0, 0, 0, 0, 0, 0, 0, 1]  237672660_0044         amc  2018   
834     [0, 0, 0, 0, 0, 0, 0, 0, 1]  237672660_0046         amc  2018   
...                             ...             ...         ...   ...   
215368  [0, 0, 0, 0, 0, 0, 0, 1, 0]  439612646_0095         amc  2020   
215369  [0, 0, 0, 0, 0, 0, 0, 1, 0]  439612646_0096         amc  2020   
216714  [1, 0, 0, 0, 0, 0, 0, 0, 0]  412486717_0008         amc  2020   
216744  [1, 0, 0, 0, 0, 0, 0, 0, 0]  421615189_0007         amc  2020   
217791  [1, 0, 0, 0, 0, 0, 0, 0, 0]  423659267_0010        vumc  2020   

            MDN  NotitieID      batch annotator  background_sent  target_sent  \
821     6223307  237672660    week_18  katsburg            False        False   
827     6223307  237672660    week_18  katsburg            False        False   
831     6223307  237672660    week_18  katsburg            False        False   
832     6223307  237672660    week_18  katsburg            False        False   
834     6223307  237672660    week_18  katsburg            False        False   
...         ...        ...        ...       ...              ...          ...   
215368  3850656  439612646  ze_batch1     hinke            False        False   
215369  3850656  439612646  ze_batch1     hinke            False        False   
216714  1644335  412486717  ze_batch1     hinke            False        False   
216744  2844805  421615189  ze_batch1     hinke            False        False   
217791  6571053  423659267  ze_batch1     hinke            False        False   

                                                                                                                                                                    text_raw  \
821                                                                      

In [5]:
test_preds['domain_pred'] = ""

In [6]:
test_preds['domain_gold'] = ""

In [7]:
for ri, row in test_preds.iterrows():
    if row['labels'] == [1, 0, 0, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'ADM'
    if row['labels'] == [0, 1, 0, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'ATT'
    if row['labels'] == [0, 0, 1, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'BER'
    if row['labels'] == [0, 0, 0, 1, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'ENR'
    if row['labels'] == [0, 0, 0, 0, 1, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'ETN'
    if row['labels'] == [0, 0, 0, 0, 0, 1, 0, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'FAC'
    if row['labels'] == [0, 0, 0, 0, 0, 0, 1, 0, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'INS'
    if row['labels'] == [0, 0, 0, 0, 0, 0, 0, 1, 0]:
        test_preds.loc[ri, 'domain_pred'] = 'MBW'
    if row['labels'] == [0, 0, 0, 0, 0, 0, 0, 0, 1]:
        test_preds.loc[ri, 'domain_pred'] = 'STM'
    #if row['labels'] == [0, 0, 0, 0, 0, 0, 0, 0, 0]:
     #   test_preds.loc[ri, 'domain_pred'] = 'O'

In [8]:
for ri, row in test_preds.iterrows():
    if row['original_labels'] == [1, 0, 0, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'ADM'
    if row['original_labels'] == [0, 1, 0, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'ATT'
    if row['original_labels'] == [0, 0, 1, 0, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'BER'
    if row['original_labels'] == [0, 0, 0, 1, 0, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'ENR'
    if row['original_labels'] == [0, 0, 0, 0, 1, 0, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'ETN'
    if row['original_labels'] == [0, 0, 0, 0, 0, 1, 0, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'FAC'
    if row['original_labels'] == [0, 0, 0, 0, 0, 0, 1, 0, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'INS'
    if row['original_labels'] == [0, 0, 0, 0, 0, 0, 0, 1, 0]:
        test_preds.loc[ri, 'domain_gold'] = 'MBW'
    if row['original_labels'] == [0, 0, 0, 0, 0, 0, 0, 0, 1]:
        test_preds.loc[ri, 'domain_gold'] = 'STM'
    #if row['original_labels'] == [0, 0, 0, 0, 0, 0, 0, 0, 0]:
     #   test_preds.loc[ri, 'domain_gold'] = 'O'

In [9]:
test_preds

text  \
821                                                                         Anamnese M is wel nerveus over dit gesprek , bang dat we iets doorvertellen aan instanties .   
827                                                                                                                M is niet bang , wil ook geen aangifte of scheiding .   
831                                                             Heeft het vechten nooit gezien , maar ziet wel dat moeder dan boos is , heeft het mogelijk ook gehoord .   
832                                                                         PERSON is nooit geslagen , P is niet boos op de kinderen , alleen op PERSON slaat ook niet .   
834                                                                                                                                           PERSON lijkt wel bezorgd .   
...                                                                                                                                                                  ...   
215368                                                                                                                                         Ondervoeding - SNAQ Score   
215369                                                                                                                                                              SNAQ   
216714                                                                                                                                              37,4 ° C | Ademhal .   
216744                                                                                                                                                    Geen dyspnoe .   
217791  Bloeddruk 117/75 , polsfrequentie 110 , temperatuur 35,5 ° C , temperatuurbron PERSON , ademhalingsfrequentie 14 , lengte 170 cm , gewicht 76,8 kg , SpO2 97 % .   

                             labels      pad_sen_id institution  year  \
821     [0, 0, 0, 0, 0, 0, 0, 0, 1]  237672660_0033         amc  2018   
827     [0, 0, 0, 0, 0, 0, 0, 0, 1]  237672660_0039         amc  2018   
831     [0, 0, 0, 0, 0, 0, 0, 0, 1]  237672660_0043         amc  2018   
832     [0, 0, 0, 0, 0, 0, 0, 0, 1]  237672660_0044         amc  2018   
834     [0, 0, 0, 0, 0, 0, 0, 0, 1]  237672660_0046         amc  2018   
...                             ...             ...         ...   ...   
215368  [0, 0, 0, 0, 0, 0, 0, 1, 0]  439612646_0095         amc  2020   
215369  [0, 0, 0, 0, 0, 0, 0, 1, 0]  439612646_0096         amc  2020   
216714  [1, 0, 0, 0, 0, 0, 0, 0, 0]  412486717_0008         amc  2020   
216744  [1, 0, 0, 0, 0, 0, 0, 0, 0]  421615189_0007         amc  2020   
217791  [1, 0, 0, 0, 0, 0, 0, 0, 0]  423659267_0010        vumc  2020   

            MDN  NotitieID      batch annotator  background_sent  target_sent  \
821     6223307  237672660    week_18  katsburg            False        False   
827     6223307  237672660    week_18  katsburg            False        False   
831     6223307  237672660    week_18  katsburg            False        False   
832     6223307  237672660    week_18  katsburg            False        False   
834     6223307  237672660    week_18  katsburg            False        False   
...         ...        ...        ...       ...              ...          ...   
215368  3850656  439612646  ze_batch1     hinke            False        False   
215369  3850656  439612646  ze_batch1     hinke            False        False   
216714  1644335  412486717  ze_batch1     hinke            False        False   
216744  2844805  421615189  ze_batch1     hinke            False        False   
217791  6571053  423659267  ze_batch1     hinke            False        False   

                                                                                                                                                                    text_raw  \
821                                                                      

In [10]:
y_pred = test_preds['domain_pred'].tolist()
y_true = test_preds['domain_gold'].tolist()

In [11]:
unique_labels = np.unique([y_true, y_pred])
cmtx = pd.DataFrame(
    confusion_matrix(y_true, y_pred, labels=unique_labels),
    index=['true:{:}'.format(x) for x in unique_labels],
    columns=['pred:{:}'.format(x) for x in unique_labels]
)

cmtx

pred:  pred:ADM  pred:ATT  pred:BER  pred:ENR  pred:ETN  pred:FAC  \
true:        57       100         1        10        28       111       115   
true:ADM      7       172         0         0         1         0         1   
true:ATT      0         0         8         0         0         0         1   
true:BER      1         0         0         6         0         0         0   
true:ENR      2         0         0         0        51         1         0   
true:ETN      0         1         0         0         0        81         2   
true:FAC      1         1         0         0         0         0        83   
true:INS      2         1         0         0         1         0         7   
true:MBW      1         0         0         0         0         0         0   
true:STM      1         0         0         0         1         0         0   

          pred:INS  pred:MBW  pred:STM  
true:           45        36        51  
true:ADM         1         0         0  
true:ATT         0         0         0  
true:BER         0         0         0  
true:ENR         0         0         0  
true:ETN         0         0         0  
true:FAC         0         0         0  
true:INS        25         0         0  
true:MBW         0        39         0  
true:STM         0         1        94

In [12]:
cf = cmtx.to_numpy()

In [13]:
tp = np.diag(cf)

precision = list(map(truediv, tp, np.sum(cf, axis = 0)))
recall = list(map(truediv, tp, np.sum(cf, axis = 1)))
f1 = []

for p, r in list(zip(precision, recall)):
    f = (2*p*r)/(p+r)
    f1.append(f)

#print('Precision: {}\nRecall: {}\nF1 score: {}'.format(precision, recall, f1))

In [14]:
results = pd.DataFrame([precision,
                       recall,
                       f1],
                      columns=['O', 'ADM', 'ATT', 'BER', 'ENR', 'ETN', 'FAC', 'INS', 'MBW', 'STM'],
                      index=['Precision','Recall', 'F1 score'])

results

O       ADM       ATT       BER       ENR       ETN  \
Precision  0.791667  0.625455  0.888889  0.375000  0.621951  0.419689   
Recall     0.102888  0.945055  0.888889  0.857143  0.944444  0.964286   
F1 score   0.182109  0.752735  0.888889  0.521739  0.750000  0.584838   

                FAC       INS       MBW       STM  
Precision  0.397129  0.352113  0.513158  0.648276  
Recall     0.976471  0.694444  0.975000  0.969072  
F1 score   0.564626  0.467290  0.672414  0.776860

In [16]:
results.to_pickle("/mnt/data/Users/A-PROOF/Cecilia_S/models/fine_tuned/best_model/results_hq1.pkl")

In [15]:
domains = ['O', 'ADM', 'ATT', 'BER', 'ENR', 'ETN', 'FAC', 'INS', 'MBW', 'STM']

for d, p, r, f in list(zip(domains, precision, recall, f1)):
    print('{}\nPrecision: {}\nRecall: {}\nF1 score: {}\n'.format(d, p, r, f))

O
Precision: 0.7916666666666666
Recall: 0.10288808664259928
F1 score: 0.18210862619808307

ADM
Precision: 0.6254545454545455
Recall: 0.945054945054945
F1 score: 0.7527352297592999

ATT
Precision: 0.8888888888888888
Recall: 0.8888888888888888
F1 score: 0.8888888888888888

BER
Precision: 0.375
Recall: 0.8571428571428571
F1 score: 0.5217391304347825

ENR
Precision: 0.6219512195121951
Recall: 0.9444444444444444
F1 score: 0.7500000000000001

ETN
Precision: 0.41968911917098445
Recall: 0.9642857142857143
F1 score: 0.5848375451263538

FAC
Precision: 0.39712918660287083
Recall: 0.9764705882352941
F1 score: 0.564625850340136

INS
Precision: 0.352112676056338
Recall: 0.6944444444444444
F1 score: 0.4672897196261682

MBW
Precision: 0.5131578947368421
Recall: 0.975
F1 score: 0.6724137931034483

STM
Precision: 0.6482758620689655
Recall: 0.9690721649484536
F1 score: 0.7768595041322313



In [16]:
counter = 0

for ri, row in test_preds.iterrows():
    if row['domain_gold'] == '' and row['domain_pred'] == '':
        counter += 1
        
print(counter)

57


### Old

In [32]:
cf_matrix = confusion_matrix(y_true, y_pred)

In [33]:
print(cf_matrix)

[[ 15   9   0   2   6   2  15  12   6   1   2]
 [  7 172   0   0   1   0   1   1   0   0   0]
 [  0   0   8   0   0   0   1   0   0   0   0]
 [  0   0   0   6   0   0   0   0   0   1   0]
 [  2   0   0   0  51   1   0   0   0   0   0]
 [  0   1   0   0   0  81   2   0   0   0   0]
 [  1   1   0   0   0   0  83   0   0   0   0]
 [  2   1   0   0   1   0   7  25   0   0   0]
 [  1   0   0   0   0   0   0   0  39   0   0]
 [ 20  91   1   8  22 109 100  33  30  21  49]
 [  0   0   0   0   1   0   0   0   1   1  94]]
